### PR TITLE
Refactor Universe build into smaller, more parallel steps

### PR DESCRIPTION
**Pull request by natemcmaster**
Massive refactoring is still WIP, so this PR is still targeting the <kbd>feature/repo-proj</kbd> branch.

Changes:
 - Build each of the following in a separate MSBuild project.
     - Metapackage
     - RuntimeStore
     - LZMA
     - Templating
     - All "normal" aspnet repos
     - Runtime store installers
 - Add a solution file named "Microsoft.AspNetCore.sln" (not for actual use in VS). It has the following solution configurations/platforms
    - Debug/linux-x64
    - Debug/osx-x64
    - Debug/win-x64
    - Debug/win-x64
    - Release/linux-x64
    - Release/osx-x64
    - Release/win-x64
    - Release/win-x64
 - Make the metapackage and runtimestore builds faster by generating a nuspec, instead of generating an MSBuild project, calling restore, and then invoking msbuild /t:Pack to generate the nuspec.
 - Add dotnet-archive to this repo (yes, I hate myself for this. This is temporary until we fix https://github.com/aspnet/Universe/issues/595).

cc @pakrym  @JunTaoLuo @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
What's the motivation for doing this? How much build time do we end up saving with these changes? It's a considerable amount of code churn and I want to understand if there are good motivations for this - both for you to write and for the reviewers.

**Comment by pakrym** [comment]
I'm also concerned with the need to track repo to repo dependencies in multiple places. I feel we are not moving towards simplifying usage of the universe but instead making it a bit harder.

**Comment by natemcmaster** [comment]
Primary motivations
1. It makes it easier for devs to build and run build steps that depend on having a complete version of the shared framework/runtime store. i.e MusicStore, Templating, Azure Integration. cc @pakrym for the Azure site extension
2. Lays the foundation for incremental builds. With this, you can manually do incrementalism by executing `dotnet build --no-dependencies Mvc.repoproj` (sugar for `dotnet msbuild /p:BuildProjectReferences=false Mvc.repoproj`) to build as if in universe, but to skip rebuilding dependencies. Next thing I hope to add is automatic incrementalism. This factoring of Universe allows us to better define the inputs/outputs of each segment of the build.
3. Speed due to better parallelism. On my machine, building the repos saves 5-8 minutes.

**Comment by natemcmaster** [comment]
Motivation 4. source-build. We need to be able to our stack completely from one machine, end-to-end. You cannot currently build universe end-to-end and get templates, packages, runtime store, and metapackage. You have to manually imitated what TeamCity does (move files to .deps/ folders) and fan out the build to multiple operating systems. This change doesn't fix this completely, but it's a step in that direction.

**Comment by natemcmaster** [comment]
@pakrym did you see this? https://github.com/aspnet/Universe/pull/696

**Comment by pranavkm** [comment]
Can this be broken down to individual items?

**Comment by natemcmaster** [comment]
Break down what? This PR? It doesn't implement incrementalism, source-build, or the build-on-one-machine thing yet. Those are just things that that this approach enables us to do next.

I know this is a big change, but if you want to see the important pieces of this PR in separate PRs, you can do this already with GH. I thought it was important to demonstrate that this approach could work end to end (from Common thru LZMA + RuntimeStore)

 - Initial implementation of repoproj: https://github.com/aspnet/Universe/pull/739/commits/aae6c9c4929ff538af66440961a9a9e91455f5c1
 - Porting runtime store targets: https://github.com/aspnet/Universe/pull/739/files/1377af387bf63bccff04064c5e2394b48c4e0e45..6029a73327d3eb886b3c2d3957a06b8d2450c069
 - Port LZMA targets https://github.com/aspnet/Universe/pull/739/commits/f19780abcdba644c08a6ea7d58015429f316b19c

**Comment by natemcmaster** [comment]
🔔

**Comment by pranavkm** [comment]
Let's look at this in preview2. @natemcmaster do you want to maybe set up a PR review meeting for this and we could just walk us through the interesting parts?

**Comment by natemcmaster** [comment]
Will do.

**Comment by natemcmaster** [comment]
Closing this particular iteration of this work. We discussed as team. Although we like the approach, we'd rather invest this effort towards the 2.1 branch. This PR was based on 2.0, so needs to be reworked quite a bit. Also, we want to break down this refactoring into smaller chunks, so I'll be working on rolling this approach out in pieces.

**Pull request closed without merging**
