### PR TITLE
Update branding to 2.1.6

### PR DESCRIPTION
**Pull request by natemcmaster**
Prepare universe to build patches of 2.1.6.

@ajcvickers @muratg @Eilon - which repos have approved bugs for 2.1.6? Right now, this PR would only update metapackages.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Looks like there is this one too: https://github.com/aspnet/Common/pull/399

**Comment by Eilon** [comment]
Oh yes that one too

**Comment by ajcvickers** [comment]
@natemcmaster We have a 2.1.6 issue for Identity. Nothing for EF...yet...touch wood.

**Comment by natemcmaster** [comment]
:up: :date:

**Pull request merged**
