### PR TITLE
Reduce the number of directories we look for projects to build in.

### PR DESCRIPTION
**Pull request by pranavkm**
cc @victorhurdugaci \ @moozzyk \ @natemcmaster 

Not super sure if this is something that is correct to do. A cursory scan of our projects suggests we don't have src, test or samples nested beyond the first level. In Mvc, we have test websites that are nested. However they are built as dependencies to our functional tests so we can avoid rebuilding them separately.

### CODE REVIEW

**Comment by moozzyk** [comment]
:ship::it:

**Comment by victorhurdugaci** [comment]
Looks good :shipit:

**Comment by natemcmaster** [comment]
:shipit:

**Comment by victorhurdugaci** [comment]
Please make this change in https://github.com/aspnet/KoreBuild too

**Pull request closed without merging**
