### PR TITLE
#228 / #229 - build.sh - parameter expansion, output redirection

### PR DESCRIPTION
**Pull request by dmccaffery**
Corrected issues in build.sh and build-template/build.sh which could cause the script to fail when wget was missing, or the $HOME path contained an unescaped sequence (such as a space).

- Quoted parameter where variable expansion could result in an unescaped sequence.
- Added output redirection token for curl when wget is not present or otherwise fails.

#228
#229

### CODE REVIEW

**Comment by dmccaffery** [comment]
Reopened the pull request to pickup the cla-already-signed label; my signature was stuck for a bit.

**Comment by muratg** [comment]
@pranavkm, @dmccaffery is this still a useful PR?

**Comment by dmccaffery** [comment]
Probably. Let me test it again since its been awhile since the original PR was issued. Can I report back to you tomorrow?

**Comment by muratg** [comment]
@dmccaffery sounds good, thanks!

**Comment by muratg** [comment]
Closing this one. @dmccaffery Thanks, and please feel free to send another one if you're still having issue.

**Pull request closed without merging**
