### PR TITLE
Add web.administation as an external dependency.

### PR DESCRIPTION
**Pull request by jkotalik**
Required for https://github.com/aspnet/IISIntegration/pull/979

### CODE REVIEW

**Comment by pakrym** [comment]
LGTM

**Comment by natemcmaster** [comment]
Should this target release/2.2?

**Comment by jkotalik** [comment]
Retargeted.

**Comment by natemcmaster** [comment]
Btw, don't worry about merging this back to dev. I'm working on finishing the 2.2/3.0 branding changes on our repos

**Comment by natemcmaster** [comment]
Don't forget to merge this :)

**Pull request merged**
