### PR TITLE
Add BrowserLink

### PR DESCRIPTION
**Pull request by victorhurdugaci**
@jodavis

### CODE REVIEW

**Comment by pranavkm** [comment]
The repo doesn't have any code in it as yet? Should we wait until it is populated?

**Comment by victorhurdugaci** [comment]
It has in the dev branch

**Comment by NTaylorMullen** [comment]
Be sure to update the `NuGet.config` to v3 (didn't get browser link because it wasn't in Universe yet).

**Comment by muratg** [comment]
:shipit: once you make the NuGet.config change as well.

**Comment by muratg** [comment]
:watch:

**Pull request merged**
