### PR TITLE
Update to latest `dnvm`

### PR DESCRIPTION
**Pull request by dougbu**
- beta6-10394 to beta8-15517
  - grabbed from aspnet/Home but left default feed URIs alone
  - includes important fixes such as `dnvm use alias -r coreclr` support

### CODE REVIEW

**Comment by dougbu** [comment]
/cc @BrennanConroy @natemcmaster 

@natemcmaster this is an alternate to #278 now that aspnet/dnvm#422 is fixed.

**Comment by dougbu** [comment]
@BrennanConroy ping

**Comment by BrennanConroy** [comment]
:shipit:

**Comment by dougbu** [comment]
345c598

**Pull request closed without merging**
