### PR TITLE
Add KeyPerFile to ship

### PR DESCRIPTION
**Pull request by HaoK**
Part of https://github.com/aspnet/Configuration/pull/784, renaming DockerSecrets and marking it ship

### CODE REVIEW

**Comment by HaoK** [comment]
I can do this in two steps right?  Or will Universe build break when dockersecrets is removed?

**Comment by natemcmaster** [comment]
it will break if you merge this PR as is. The PR checks that are failing on this PR are legit errors. 

https://travis-ci.org/aspnet/Universe/builds/358575833?utm_source=github_status&utm_medium=notification
https://ci.appveyor.com/project/aspnetci/universe/build/1.0.1080

```
C:\projects\universe\build\repo.targets(154,5): error : Undeclared package artifacts. Add these to artifacts.props: [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview2-15749\KoreBuild.proj]
C:\projects\universe\build\repo.targets(154,5): error :   - Microsoft.Extensions.Configuration.DockerSecrets [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview2-15749\KoreBuild.proj]
```

**Comment by HaoK** [comment]
I meant merging the Configuration PR without updating universe, but it sounds like both will need to go in together

**Comment by natemcmaster** [comment]
I see. Merging the configuration PR first is the better approach so you know the exact commit hash of the submodule you should manually add to this Universe update. This kind of change is a thing our automation can't currently handle.

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/Universe/pull/1004

**Pull request closed without merging**
