### PR TITLE
Update to NETStandard.Library 2.0.2

### PR DESCRIPTION
**Pull request by natemcmaster**
Includes major build-perf improvements. See https://github.com/dotnet/standard/releases/tag/v2.0.2

@pranavkm - required to adopt new SDK.

### CODE REVIEW

**Comment by pranavkm** [comment]
Any idea what's up with AppV?

**Comment by pranavkm** [comment]
> :/projects/universe/modules/Mvc/src/Microsoft.AspNetCore.Mvc.ApiExplorer/Microsoft.AspNetCore.Mvc.ApiExplorer.csproj : error KRB4005: Undefined external dependency on NETStandard.Library/2.0.1 [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-rc1-15773\KoreBuild.proj]

Do we need to explicitly bump up the NS Library Implicit version?

**Comment by natemcmaster** [comment]
I was just working on this. It looks like we're missing the same overrides that we have for implicit versions of Microsoft.NEtCore.App. I was about to commit this change to all repos.

```diff
<Project>
  <PropertyGroup>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp2.0' ">$(MicrosoftNETCoreApp20PackageVersion)</RuntimeFrameworkVersion>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">$(MicrosoftNETCoreApp21PackageVersion)</RuntimeFrameworkVersion>
+   <NETStandardImplicitPackageVersion Condition=" '$(TargetFramework)' == 'netstandard2.0' ">$(NETStandardLibrary20PackageVersion)</NETStandardImplicitPackageVersion>
  </PropertyGroup>
</Project>
```

**Comment by pranavkm** [comment]
Fair enough. Can you turn off project build triggers on the CI before you push (so as to not queue up too many builds)?

**Comment by natemcmaster** [comment]
Will do.

**Comment by natemcmaster** [comment]
Huh, this is weird. MSBuild reported no errors, but it still exited with a non-zero code. Flakiness in the new SDK maybe? 
```
16:56:05]  DependencyInjection   | 
[16:56:05]  DependencyInjection   | Build succeeded.
[16:56:05]  DependencyInjection   | 
[16:56:05]  DependencyInjection   | C:\b\w\6e78c7aba2f17cd5\.packages\internal.aspnetcore.sdk\2.1.0-rc1-15774\build\ApiCheck.targets(61,5): warning : No baseline file 'C:\b\w\6e78c7aba2f17cd5\modules\DependencyInjection\src\DI\baseline.netframework.json' for net461 found in DI.
[16:56:05]  DependencyInjection   |     1 Warning(s)
[16:56:05]  DependencyInjection   |     0 Error(s)
[16:56:05]  DependencyInjection   | 
[16:56:05]  DependencyInjection   | Time Elapsed 00:00:36.30
[16:56:05]  dotnet.exe failed with exit code: 1
[16:56:05]  At C:\b\w\6e78c7aba2f17cd5\.dotnet\buildtools\korebuild\2.1.0-rc1-15774\scripts
[16:56:05]  \common.psm1:11 char:9
[16:56:05]  +         throw "$cmdName failed with exit code: $exitCode"
[16:56:05]  +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16:56:05]      + CategoryInfo          : OperationStopped: (dotnet.exe failed with exit c 
[16:56:05]     ode: 1:String) [], RuntimeException
[16:56:05]      + FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
[16:56:05]   
[16:56:05]C:\b\w\6e78c7aba2f17cd5\build\RepositoryBuild.targets(121,5): error : Building DependencyInjection failed: build.cmd exited code 1 [C:\b\w\6e78c7aba2f17cd5\.dotnet\buildtools\korebuild\2.1.0-rc1-15774\KoreBuild.proj]
```
http://aspnetci/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=451843&_focus=4500

**Comment by pranavkm** [comment]
It's the first repo with a warning. Could something be treating that as an error?

**Comment by natemcmaster** [comment]
Building Universe locally I get
```
  Common                | C:\dev\aspnet\Universe21\modules\Common\shared\Microsoft.Extensions.Buffers.Sources\BufferReader.cs(10,14): error CS8107: Feature 'ref structs' is not available in C# 7.0. Please use language version 7.2 or greater.
  Common                | C:\dev\aspnet\Universe21\modules\Common\shared\Microsoft.Extensions.Buffers.Sources\BufferWriter.cs(9,14): error CS8107: Feature 'ref structs' is not available in C# 7.0. Please use language version 7.2 or greater.
  Common                | C:\dev\aspnet\Universe21\modules\Common\shared\Microsoft.Extensions.Buffers.Sources\MemoryPoolBlock.Debug.cs(97,98): error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.
```
So I have no clue. Investigating still...

**Pull request merged**
