### PR TITLE
Handle --version in dotnet-install.sh.

### PR DESCRIPTION
**Pull request by cesarbs**
cc @pranavkm @victorhurdugaci

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
It looks okay... Does the KoreBuild.sh need to be updated too?

**Comment by cesarbs** [comment]
No,  it is calling dotnet-install.sh passing --version, the problem is that it is not handled.

**Comment by victorhurdugaci** [comment]
Okay, :shipit: it then

**Comment by cesarbs** [comment]
I actually had to change `Korebuild.sh` to pin the dotnet version to 1244, since 1249 is not available for *nix yet.

**Pull request merged**
