### PR TITLE
Update Moq to 4.11.0

### PR DESCRIPTION
**Pull request by rynowak**
This is the latest version of Moq, should have a fix for
https://github.com/aspnet/Home/issues/3569

### CODE REVIEW

**Comment by rynowak** [comment]
To verify this, I ran this locally with MVC. MVC has pretty substantial usage of Moq

**Comment by natemcmaster** [comment]
cc @Eilon for OSS approval

**Comment by rynowak** [comment]
@natemcmaster @ryanbrandenburg - any advade about these cool build failures:

> D:\a\1\s\build\repo.targets(229,5): error : The SDK 'Internal.AspNetCore.Sdk' specified could not be found.  > D:\a\1\s\modules\Mvc\src\Microsoft.AspNetCore.Mvc.RazorPages\Microsoft.AspNetCore.Mvc.RazorPages.csproj [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]
2018-10-09T16:30:39.7512999Z D:\a\1\s\build\repo.targets(229,5): error : The SDK 'Internal.AspNetCore.Sdk' specified could not be found.  > D:\a\1\s\modules\Scaffolding\test\VS.Web.CG.EFCore.Test\VS.Web.CG.EFCore.Test.csproj [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]
2018-10-09T16:30:43.5434313Z   Finished design-time build in 45311ms

**Comment by ryanbrandenburg** [comment]
@natemcmaster thinks we've fixed it with https://github.com/aspnet/Universe/pull/1469.

**Comment by natemcmaster** [comment]
Um, where do we get Moq 4.11? The latest on nuget.org is 4.10

**Pull request merged**
