### PR TITLE
Add Microsoft.AspNetCore.AzureKeyVault.HostingStartup

### PR DESCRIPTION
**Pull request by pakrym**
https://github.com/aspnet/AzureIntegration/pull/126

### CODE REVIEW

**Comment by natemcmaster** [comment]
When you merge https://github.com/aspnet/AzureIntegration/pull/126, can you also update modules/AzureIntegration to the new commit that contains this new package?

**Comment by pakrym** [comment]
@natemcmaster I can, but why is it required? Wouldn't universe build do it automatically?

**Comment by natemcmaster** [comment]
Our update scripts will do it automatically, but I still recommend this for any change to git submodules that would break Universe. If you push without updating the submodule, aspnet/Universe is broken and won't build until that updater script succeeds.

**Comment by natemcmaster** [comment]
FYI - for adding/removing packages, this should happen less once we do #686

**Pull request merged**
