### PR TITLE
Bower blocks build on first run

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/Mvc#2116
- run Bower non-interatively from our scripts
 - does not affect grunt-brower-task; programmatic Bower use never prompts
- see Bower discussion at bower/bower#1162
- FYI `$env:CI = 'TeamCity'` would work similarly but TeamCity does not set that

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
Looks good :shipit:

**Comment by DamianEdwards** [comment]
:shipit:

**Comment by dougbu** [comment]
commit f6ae75e

**Pull request closed without merging**
