### PR TITLE
React to aspnet/Logging#884

### PR DESCRIPTION
**Pull request by halter73**
Only take this if we take aspnet/Logging#884

### CODE REVIEW

**Comment by Eilon** [comment]
What's the conclusion to https://github.com/aspnet/Logging/pull/884#issuecomment-426005845 ?

**Comment by halter73** [comment]
If no one objects, I'll merge today.

**Comment by Eilon** [comment]
Can you confirm this is all used in only non-shipping stuff? If so, go ahead.

**Comment by BrennanConroy** [comment]
Looks like Serilog is only used by test projects in our org

**Comment by halter73** [comment]
Thanks @BrennanConroy

**Pull request merged**
