### PR TITLE
Ensure template tests run on CI

### PR DESCRIPTION
**Pull request by natemcmaster**
Templates tests aren't actually running on CI. 

⌚️ on @JunTaoLuo to fixup some stuff in the shared fx. Templates tests do not pass with latest builds of aspnetcore.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
SharedFX will be fixed once we ingest latest 2.2 sdk

**Comment by JunTaoLuo** [comment]
So it looks like we have ingested the new SDK, we should give the template tests another run.

**Comment by natemcmaster** [comment]
This requires some new thinking about how we test with the shared framework. Since the template tests will assume the shared fx is installed, we need to figure that bit out first.

**Comment by natemcmaster** [comment]
Opened https://github.com/aspnet/Universe/issues/713 to follow up on this

**Pull request closed without merging**
