### PR TITLE
Updating external dependencies

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
New versions:
    SystemReflectionMetadataPackageVersion
    SystemThreadingChannelsPackageVersion
    SystemRuntimeCompilerServicesUnsafePackageVersion
    SystemDataSqlClientPackageVersion
    SystemSecurityCryptographyCngPackageVersion
    SystemServiceProcessServiceControllerPackageVersion
    SystemDiagnosticsEventLogPackageVersion
    SystemSecurityPrincipalWindowsPackageVersion
    SystemNumericsVectorsPackageVersion
    SystemCollectionsImmutablePackageVersion
    SystemBuffersPackageVersion
    SystemDiagnosticsDiagnosticSourcePackageVersion
    SystemNetHttpWinHttpHandlerPackageVersion
    SystemIOPipelinesPackageVersion
    SystemThreadingTasksExtensionsPackageVersion
    SystemValueTuplePackageVersion
    SystemSecurityPermissionsPackageVersion
    MicrosoftNETCoreAppPackageVersion
    SystemComponentModelAnnotationsPackageVersion
    MicrosoftExtensionsDependencyModelPackageVersion
    MicrosoftCSharpPackageVersion
    SystemMemoryPackageVersion
    SystemThreadingTasksDataflowPackageVersion
    SystemTextEncodingsWebPackageVersion
    SystemNetWebSocketsWebSocketProtocolPackageVersion
    SystemSecurityCryptographyXmlPackageVersion
    MicrosoftWin32RegistryPackageVersion

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
@pakrym for FYI.

**Comment by pakrym** [comment]
LGTM

**Comment by pakrym** [comment]
is it automated?

**Comment by ryanbrandenburg** [comment]
This was generated by me testing #1011, which we'll add to Maestro.

**Pull request merged**
