### PR TITLE
Merge release/2.1 => dev

### PR DESCRIPTION
**Pull request by HaoK**
@natemcmaster @ryanbrandenburg not sure what the process for this merge back to dev should be, looks like lots of diffs...

### CODE REVIEW

**Comment by natemcmaster** [comment]
Here is how I merge back to dev
```
git checkout dev
git pull
git checkout -b namc/merge-rel-21
git merge --no-commit --no-ff release/2.1
git checkout dev modules/
git checkout dev build/dependencies.props
git commit
```
Then open a PR using `namc/merge-rel-21`

**Comment by pranavkm** [comment]
Can we get Update-Universe to merge back in to dev each time it checks in to release? Merging from release is not intuitive now.

**Comment by HaoK** [comment]
Replaced by https://github.com/aspnet/Universe/pull/1007

"not intuitive"...  That's a polite way of putting it :)

**Comment by natemcmaster** [comment]
> Can we get Update-Universe to merge back in to dev each time it checks in to release?

Not easily at the moment. Requires manual conflict resolution. But this pain shouldn't last beyond Friday, right?

**Pull request closed without merging**
