### PR TITLE
Build tests and samples

### PR DESCRIPTION
**Pull request by victorhurdugaci**
Turns out we're not building tests and samples anymore

cc @pranavkm @Tratcher

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by Tratcher** [comment]
Would this cause a normal `build.cmd` run to compile the tests twice? Once for `build-test` and once for `test`?

**Comment by pranavkm** [comment]
In theory, once we have incremental builds in CLI, it should no-op the second build.

**Comment by Tratcher** [comment]
But in the meantime this makes everything even slower locally? That might be a problem.

**Comment by pranavkm** [comment]
They have incremental builds working in the latest drop. We're waiting on https://github.com/dotnet/cli/pull/1067#discussion_r51060978 to go through before we switch to it. That should be soon. We could hold off on this check in until that happens.

**Comment by victorhurdugaci** [comment]
@JunTaoLuo this might impact your configurable folder change

**Comment by victorhurdugaci** [comment]
Here's the deal. I want to push this because the CI doesn't build samples, so I've added a switch that allows you to build "the old way" as a workaround for building locally in case you feel the build is too slow.

**Pull request merged**
