### PR TITLE
Updating external dependencies

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
New versions:
    SystemReflectionMetadataPackageVersion
    SystemThreadingChannelsPackageVersion
    SystemRuntimeCompilerServicesUnsafePackageVersion
    SystemDataSqlClientPackageVersion
    SystemSecurityCryptographyCngPackageVersion
    SystemServiceProcessServiceControllerPackageVersion
    SystemDiagnosticsEventLogPackageVersion
    SystemSecurityPrincipalWindowsPackageVersion
    SystemNumericsVectorsPackageVersion
    SystemCollectionsImmutablePackageVersion
    SystemBuffersPackageVersion
    SystemDiagnosticsDiagnosticSourcePackageVersion
    MicrosoftNETCoreDotNetAppHostPackageVersion
    SystemNetHttpWinHttpHandlerPackageVersion
    SystemIOPipelinesPackageVersion
    SystemThreadingTasksExtensionsPackageVersion
    SystemValueTuplePackageVersion
    SystemSecurityPermissionsPackageVersion
    MicrosoftNETCoreAppPackageVersion
    SystemComponentModelAnnotationsPackageVersion
    MicrosoftExtensionsDependencyModelPackageVersion
    MicrosoftCSharpPackageVersion
    SystemMemoryPackageVersion
    SystemThreadingTasksDataflowPackageVersion
    SystemTextEncodingsWebPackageVersion
    SystemNetWebSocketsWebSocketProtocolPackageVersion
    SystemSecurityCryptographyXmlPackageVersion
    MicrosoftWin32RegistryPackageVersion

### CODE REVIEW

**Comment by natemcmaster** [comment]
This version causes a bunch of compiler errors in .NET Framework projects, such as
```
error CS0012: The type 'Object' is defined in an assembly that is not referenced.
```

**Comment by natemcmaster** [comment]
This is why: https://github.com/dotnet/core-setup/pull/4060#issuecomment-384368199

**Comment by natemcmaster** [comment]
I've opened https://github.com/aspnet/Universe/issues/1120 to track the work on our side before we can take this.

**Comment by ryanbrandenburg** [comment]
Closing this in favor of the maestro one.

**Pull request closed without merging**
