### PR TITLE
Removed style cop related shade files

### PR DESCRIPTION
**Pull request by kichalla**
@rynowak @pranavkm Related to https://github.com/aspnet/Testing/pull/153#issuecomment-140218549

### CODE REVIEW

**Comment by muratg** [comment]
Do you need to remove it from wherever these are referenced as well?

**Comment by muratg** [comment]
Oh

**Comment by muratg** [comment]
:shipit:

**Comment by kichalla** [comment]
5008e2743d1d0992af86d98a321ac88bd979fafd

**Pull request closed without merging**
