### PR TITLE
Switch SignalR-* -> SignalR

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @davidfowl \ @Eilon 

This is for 1.1.0, right?

**Comment by Eilon** [comment]
I think it's technically for 1.2.0, no? @muratg when are we shipping these?

**Comment by pranavkm** [comment]
Gotcha. Would we be releasing the SignalR-* bits for 1.1.0? Presumably I shouldn't tinker around with the CI configuration until we branch

**Comment by muratg** [comment]
Yes, this will be a 1.2.0 RTM.  Per my last talks with @DamianEdwards, we do not want to release bits to nuget in 1.1 timeline.

**Comment by pranavkm** [comment]
Good to go now that dev's open for 1.2.0?

**Comment by muratg** [comment]
@pranavkm Yup. Ideally we won't need to branch out of dev branches until 1.2 previews.

**Pull request merged**
