### PR TITLE
Merge release/2.1 -> dev

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by HaoK** [comment]
What about the submodule update for Config, how does that get merged over?

**Comment by natemcmaster** [comment]
Good point. did you merge to dev in aspnet/Config? If so, `git submodule update --remote modules/Configuration && git add modules/Configuration`

**Comment by HaoK** [comment]
Cool this looks like the matching set of change snow...  would a cherrypick from release have worked better here?

**Comment by natemcmaster** [comment]
No, merging is the right thing. It just takes some manual effort since there isn't a good submodule merge strategy

**Pull request merged**
