### PR TITLE
Identify .Sources packages in the build graph

### PR DESCRIPTION
**Pull request by natemcmaster**
.Sources packages won't appear in the build graph as we drop their project.json files, but we still need to detect them to get the topological sorting correct.

cref https://github.com/aspnet/Routing/pull/372
cref https://github.com/aspnet/Coherence-Signed/issues/379

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit: as long as it works

**Comment by natemcmaster** [comment]
Here's the result, when run against aspnet/Routing#372 and aspnet/Common#179

image

**Comment by pranavkm** [comment]
The build log has a bunch of warnings from being unable to parse comments:

 Failed to parse /datadrive/169923259d6dcfec/Universe/Common/NuGetPackageVerifier.json : Illegal character (char)'47' (Unicode hexadecimal 002F).

Can we clean up the verifier json \ remove the verifier parsing from here?

**Comment by natemcmaster** [comment]
We can turn off the logging line for now. I added both folder search and ngpv.json parsing in the absence of strong conventions about our .Sources packages. I'm in favor of the convention as we can also add a korebuild task to pack all /shared/*.Sources folders as contentFiles packages. We can add this as trailer to https://github.com/aspnet/Coherence-Signed/issues/379

**Comment by pranavkm** [comment]
>  pack all /shared/*.Sources folders as contentFiles packages
👍 

Could you file a work item to track this work?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/KoreBuild/issues/147

**Pull request merged**
