### PR TITLE
Merge release/2.1 into dev

### PR DESCRIPTION
**Pull request by jkotalik**
@natemcmaster I think I got it right this time. 😄 Should I remove any changes to build/dependencies.props?

### CODE REVIEW

**Comment by jkotalik** [comment]
I think the failures are due to the signalR submodule not being updated on appveyor.

**Comment by natemcmaster** [comment]
No, you can keep deps.props changes. We want those updates in dev, right @pakrym ?

**Comment by jkotalik** [comment]
@anurse do I need to upgrade submodules to pickup the breaking changes to SignalR?

**Comment by pakrym** [comment]
@natemcmaster should be fine to merge them.

**Comment by jkotalik** [comment]
@natemcmaster SignalR's breaking changes were updated in dev. I re-ran appveyor and it's green now as dev was updated. :shipit: ?

**Comment by natemcmaster** [comment]
:shipit:

**Pull request merged**
