### PR TITLE
Remove the WebSocketAbstractions repo.

### PR DESCRIPTION
**Pull request by Tratcher**
#233 @Eilon

### CODE REVIEW

**Comment by pranavkm** [comment]
Could you also add `AntiForgery` while you're at it?

**Comment by Tratcher** [comment]
In release?

**Comment by Eilon** [comment]
:shipit: for this.

**Comment by pranavkm** [comment]
Sorry that would be dev only. Maybe change it when merging release -> dev

**Comment by Tratcher** [comment]
@pranavkm I added Antiforgery for dev. You'd also forgotten to merge release->dev after the last branching.

**Pull request merged**
