### PR TITLE
Re-add ExperimentalVersions

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
These values seem to have gotten removed in a bad merge. We need them for `Microsoft.AspNetCore.Analyzers`.

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @JunTaoLuo looks like your merge...oops

@ryanbrandenburg hold up, we need other stuff too

**Comment by natemcmaster** [comment]
Compare https://github.com/aspnet/Universe/blob/release/2.1/version.props

**Comment by JunTaoLuo** [comment]
Ah yes, I took all the dev changes when resolving conflicts. Let me see what else might be missing.

**Comment by JunTaoLuo** [comment]
Looks like the two commits https://github.com/aspnet/Universe/commit/f99426db159f28fa67731bb63aa4347d8ee1a2dd and https://github.com/aspnet/Universe/commit/b37880c98526665cee33d37e6e8b5e1aee7dc267 are the only missing ones.

**Comment by natemcmaster** [comment]
Should experimentalversion in dev be `0.1.0-alpha2-$buildnumber` now?

@pranavkm  https://github.com/aspnet/Logging/blob/dev/version.props#L6 is building as 0.1.0-alpha1...the same as the release/2.1 branch

**Comment by pranavkm** [comment]
Yeah, that makes sense. @ryanbrandenburg could you make this alpha2 and I'll update the other repos.

**Pull request merged**
