### PR TITLE
Include ApiDescription.Design in artifacts

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
@dougbu it seems that the nupkg you're generating doesn't contain version information:
```
error : Could not detect version information for package id: [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview2-20181011.2\KoreBuild.proj]
error :  * Microsoft.Extensions.ApiDescription.Design [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview2-20181011.2\KoreBuild.proj]
```

please resolve this.

**Comment by natemcmaster** [comment]
The error message in universe could be made better. What it really means in this is that artifacts.props was update with a new package, but the update the Mvc submodule with the project producing that package was not made at the same time.

I've updated this PR with the MVC submodule update

**Comment by dougbu** [comment]
> I've updated this PR with the MVC submodule update

Thanks @natemcmaster! I was about to send a very similar couple of commits 😄

----
Did the CI check succeed? I expected it to fail because the CORS submodule is also out-of date and the MVC `release/2.2` branch includes a "React to CORS changes" commit.

**Comment by dougbu** [comment]
Good news is UniverseCoherence got passed building MVC. Slightly-less good news is changes in at least the following repos aren't in Universe yet:
- modules/AzureIntegration
- modules/CORS
- modules/EntityFrameworkCore
- modules/IISIntegration
- modules/Identity
- modules/KestrelHttpServer
- modules/Scaffolding
- modules/SignalR
- modules/Templating

Worse, UniverseCoherence **failed** because a property seemed to be set incorrectly. I found the typo in MVC's Microsoft.Extensions.ApiDescription.Design.csproj file and will send a "fix build" PR for that repo shortly.

**Pull request merged**
