### PR TITLE
Rename Cosmos package

### PR DESCRIPTION
**Pull request by ajcvickers**
From Microsoft.EntityFrameworkCore.Cosmos.Sql to Microsoft.EntityFrameworkCore.Cosmos

Paired with: https://github.com/aspnet/EntityFrameworkCore/pull/13533

### CODE REVIEW

**Comment by ajcvickers** [comment]
EF side merged. Waiting for review on this change.

**Comment by natemcmaster** [comment]
PR validation build fails with

> 2018-10-08T21:56:06.1787565Z D:\a\1\s\build\repo.targets(98,5): error : Could not detect version information for package id: [D:\a\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]
> 2018-10-08T21:56:06.1789504Z D:\a\1\s\build\repo.targets(98,5): error :  * Microsoft.EntityFrameworkCore.Cosmos

You'll need to also manually update the submodule to avoid breaking the build.

**Comment by ajcvickers** [comment]
@natemcmaster Are there instructions on how to do this? (Haven't done it in a long time.)

**Comment by natemcmaster** [comment]
Let me know if this explanation is enough: https://github.com/aspnet/Universe/blob/master/docs/Submodules.md#saving-an-update-to-a-submodule

**Comment by ajcvickers** [comment]
Closed in favor of https://github.com/aspnet/Universe/pull/1467

**Pull request closed without merging**
