### PR TITLE
Append commit hash to metapackages

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses https://github.com/aspnet/Universe/issues/962. Not importing the internal SDK since we don't want the reference to show up as the dependency of the metapackage.

### CODE REVIEW

**Comment by natemcmaster** [comment]
>  Not importing the internal SDK since we don't want the reference to show up as the dependency of the metapackage.

Can we set PrivateAssets = All?

Also, let's get signoff from managers first. I see you self-triaged #962. We haven't agreed to do this yet because NuGet is working on a built-in mechanism for this, so this may be unnecessary.

**Comment by JunTaoLuo** [comment]
Where is the work for the built-in mechanism being tracked?

**Comment by natemcmaster** [comment]
https://github.com/NuGet/NuGetGallery/issues/4941

**Comment by natemcmaster** [comment]
We already embed repository commit into the package metadata (by setting the [RepositoryCommit ](https://github.com/aspnet/BuildTools/pull/586) property), but the NuGet gallery and UI doesn't show it yet.

**Comment by JunTaoLuo** [comment]
Ah yes, @ajaybhargavb and I were wondering why that wasn't being displayed yesterday. Didn't know there's a plan on making that available. @davidfowl would it be sufficient if we push nuget to expose RepositoryCommit instead of us injecting it into the description or would we want both?

**Comment by natemcmaster** [comment]
I wonder if we could make a PR to NuGet to add this. I poked through their code, and it seems like it shouldn't be hard to improve the nuget gallery to show this. And it would light up for our 2.1 packages, which already have the commit metadata.

**Comment by davidfowl** [comment]
Do both? If @DamianEdwards tells me that he's super had that its in the description then maybe. But I can view it on the website without having to download or unzip anything and thats really what I want.

Do we also have it in assembly metadata?

**Comment by DamianEdwards** [comment]
I don't mind either way

**Comment by davidfowl** [comment]
@JunTaoLuo add the repository url metadata and do this.

**Comment by JunTaoLuo** [comment]
Moving the implementation to https://github.com/aspnet/BuildTools/pull/678. Initially thought we don't use the internal aspnetcore sdk for building metapackage but we do. There's no point in copying the implementation in multiple locations.

**Pull request closed without merging**
