### PR TITLE
[2.1]: Include scaffolding packages in the patch

### LINKED ISSUE #935: Scaffolding package versions need to match Microsoft.AspNetCore.App package versions
Since the `Microsoft.AspNetCore.App` package uses '=' for dependency versions, the scaffolding packages need to match the version of `Microsoft.AspNetCore.App`.

This will be implicitly true till we RTM 2.1, but for later patch builds this needs to be ensured.

cc @natemcmaster, @Eilon, @seancpeters

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #935 by bumping scaffolding to 2.1.2 and including them in the patch .

cc @vijayrkn @muratg

### CODE REVIEW

**Comment by vijayrkn** [comment]
@muratg - I have already requested the approval

**Comment by natemcmaster** [comment]
I'm back from vacation. I dug out of my email mountain, but didn't see resolution on this. Was this change approved for 2.1.2?

**Comment by vijayrkn** [comment]
This is approved for 2.1.3. I have updated the status.

**Comment by natemcmaster** [comment]
Thanks. Closing for now as this will need to be redone after rebasing on 2.1.3 changes.

**Pull request closed without merging**
