### PR TITLE
Pin to stable 2.1.0 corefx packages

### PR DESCRIPTION
**Pull request by natemcmaster**
ProdCon will not pass in versions to us for these packages because they are not patching.

⚠️ there is some danger here. If corefx decides to patch one of these packages, this change could go undetected. @weshaggard @mmitche - thoughts on how we might prevent this from happening in the future?

cc @muratg

### CODE REVIEW

**Comment by natemcmaster** [comment]
:up: :date: I added a task that will fail if ProdCon begins to pass us a new, unexpected version variable that is still in the "pinned" section.

**Comment by natemcmaster** [comment]
Merging to unblock CI.

**Comment by weshaggard** [comment]
@natemcmaster is there a reason you guys have a pinned vs non-pinned set? We simply keep one set and if it is passed by prodcon it will get overwritten if it isn't then it will just used what is checked in.

**Comment by natemcmaster** [comment]
Yes. We want to know exactly what we will be consuming in a ProdCon build. What corefx decides to patch has a ripple effect on which aspnet packages need to patch. Our infrastructure can't automate that piece yet, so we'd rather have it fail than produce an incorrect build.

**Comment by mmitche** [comment]
@weshaggard Changes in the shipping core package set will require changes in the aspnet sources.  This ensures that aspnet makes the required changes in their repos.

**Comment by mmitche** [comment]
What he said.

**Comment by weshaggard** [comment]
I don't think that is going to scale longer-term so I hope we can find a better way.

**Comment by natemcmaster** [comment]
Agreed. We're looking into automating this, but don't have time to build and test that automation before the cutoff for 2.1.1

**Pull request merged**
