### PR TITLE
`Console-Write` does not exist

### PR DESCRIPTION
**Pull request by dougbu**
- caused `dnvm use default -p` failures

### CODE REVIEW

**Comment by troydai** [comment]
@dougbu the actual source of `dnvm.ps1` is here https://github.com/aspnet/dotnetsdk/tree/dev/src. The fix should be done over there and bring back here.

The fix itself looks good. Thanks.

**Comment by troydai** [comment]
Move to dotnetsdk repo and :shipit:

**Comment by dougbu** [comment]
Pushed as aspnet/dotnetsdk@0388cd0

/cc @troydai could you copy this to aspnet/Universe please?

**Comment by troydai** [comment]
Yes, will do.

**Pull request closed without merging**
