### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by ahsonkhan**
Required to get new MemoryMarshal APIs

See: https://github.com/aspnet/KestrelHttpServer/pull/2222

cc @pakrym, @davidfowl, @BrennanConroy, @KrzysztofCwalina, @natemcmaster, @jkotas, @joshfree

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Is a new runtime also required?

**Comment by ahsonkhan** [comment]
> Is a new runtime also required?

I don't think so. As far as I can tell, Kestrel relies on slow span and OOB System.Memory, which contains the new APIs. If it relies on fast span and the inbox version of System.Memory, then we would need to update the runtime.

Why do you ask?

**Comment by pakrym** [comment]
Please update `MicrosoftNETCorePlatformsPackageVersion`. Also we don't build universe in PR so you have to verify updates locally.

**Comment by pakrym** [comment]
Closing in favor of https://github.com/aspnet/Universe/pull/718

**Pull request closed without merging**
