### PR TITLE
Copy msbuild artifacts from individual repos to universe artifacts fo…

### PR DESCRIPTION
**Pull request by kichalla**
…lder

### CODE REVIEW

**Comment by natemcmaster** [comment]
Why not just set TeamCity to gather `.r/*/artifacts/**/*`?

**Comment by kichalla** [comment]
> Why not just set TeamCity to gather .r/*/artifacts/**/*?

I wanted to do that but wouldn't it require to do this on all the nodes which build Universe or is there a better way? (like inheriting team city Project?...but probably all nodes might not have a common parent project node)

**Comment by natemcmaster** [comment]
By nodes I assume you mean build configurations. Currently, most universe builds are unique, so yes you'd have to edit several configs. 

But I'd prefer that to adding a lot of disk IO required to copy what might be thousands of files up a few folders.

**Comment by kichalla** [comment]
> But I'd prefer that to adding a lot of disk IO required to copy what might be thousands of files up a few folders.

I initially wanted to avoid 'copying' files as it also adds time to the build but based on the current universe msbuild log performance summary I noticed that the time taken by Copy task is insignificant compared to others. I was also trying to figure out if I could just pass in a property to individual repos so that they could write the artifacts directly to the root's artifacts folder, but the problem is the msbuild artifacts folder is being created in Korebuild scripts. 

Not clear about 'thousands of files'...we are copying 2 files from the 'msbuild' folder of all repos to the root, which would be like ~90 files I think

We could see if this change makes the perf worse and if it does could revert it.

**Comment by natemcmaster** [comment]
Yeah, 'thousands of files' is a exaggeration. Still seems to me like the simpler answer is to just change teamcity settings, but I'll sign of if you change the Copy to a Move instead. At least with a Move, we don't run the risk of redundant copies in the artifacts captured by TeamCity.

**Comment by kichalla** [comment]
Sure I updated to use Move and checked it in. I will keep an eye on the build time it adds
88f81f00e91c41bf3f3e5274837c56c404fbda1c

**Pull request closed without merging**
