### PR TITLE
Put ApplicationInsights.HostingStartup back into metapackage

### PR DESCRIPTION
**Pull request by pakrym**

### CODE REVIEW

**Comment by muratg** [comment]
cc @glennc FYI

**Comment by JunTaoLuo** [comment]
Do we want to continue marking this as privateassets=none? If not we need to change this as well https://github.com/aspnet/Universe/blob/rel/2.0.3/build/tasks/AddMetapackageReferences.cs#L57

**Comment by pakrym** [comment]
At least in patch we do.

**Comment by natemcmaster** [comment]
Everything in 2.0.0 was PrivateAssets=None, so we should leave this as is to maintain compatibility.

**Pull request merged**
