### PR TITLE
Update supported installer platforms

### PR DESCRIPTION
**Pull request by JunTaoLuo**
These are the new installer platforms required for the April patches.

Remove ubuntu 17.04
Add ubuntu 17.10
Add ubuntu 18.04

### CODE REVIEW

**Comment by natemcmaster** [comment]
@JunTaoLuo was there an issue tracking this? Changes look fine, but I didn't see if there was approval required.

cc @muratg

**Comment by JunTaoLuo** [comment]
I'll create an issue. This was an ask from an email from @leecow. Apparently I was the only one on it so I'm not sure folks were aware.

**Comment by JunTaoLuo** [comment]
https://github.com/aspnet/Universe/issues/971

**Comment by JunTaoLuo** [comment]
@muratg The 2.1 installers are platform agnostic so there's no need to update them.

**Pull request merged**
