### PR TITLE
Updating dotnet cli version for non-windows

### PR DESCRIPTION
**Pull request by moozzyk**
Removing DOTNET_HOME as it is no longer used

### CODE REVIEW

**Comment by moozzyk** [comment]
/cc @victorhurdugaci 
I was able to locally build the Common repo and run tests

**Comment by victorhurdugaci** [comment]
Can you also update the win version?

**Comment by moozzyk** [comment]
I guess I can but need to see if it works

**Comment by moozzyk** [comment]
:up::date:

**Comment by victorhurdugaci** [comment]
Nice! :shipit: if it works

**Pull request merged**
