### PR TITLE
Change native compilation to use VC++ 2015 instead of VC++ 2013.

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
For you @pranavkm!

**Comment by pranavkm** [comment]
Would this work for the native code in XRE? cc @davidfowl

**Comment by pranavkm** [comment]
cc @ChengTian

**Comment by ChengTian** [comment]
@pranavkm , I think you mentioned that we will have this in Beta3 release. Why is this PR targeting `dev` branch?

**Comment by pranavkm** [comment]
Sorry, this was for the rc branch. My bad.

**Comment by ChengTian** [comment]
XRE isn't using the standard goal to compile native code. XRE/makfile.shade has hard-coded path to MSBuild 14: https://github.com/aspnet/XRE/blob/dev/makefile.shade#L52

**Comment by davidfowl** [comment]
We use both now

**Pull request closed without merging**
