### PR TITLE
Update to preview2-26330-05

### PR DESCRIPTION
**Pull request by pakrym**
This one does't have breaking changes in Memory

### CODE REVIEW

**Comment by pakrym** [comment]
I'm going to merge it and see if it builds on CI, revert if something fails.

**Comment by davidfowl** [comment]
Are the other repos broken?

**Comment by pakrym** [comment]
No, memory changes are not in this PR.

**Comment by natemcmaster** [comment]
So, this is identical to the changes made by @dotnet-maestro-bot in https://github.com/aspnet/Universe/pull/1024 except for one. Any reason this excludes the NuGetFrameworksPackageVersion update?

**Pull request merged**
