### PR TITLE
Branching needs to account for libuv

### LINKED ISSUE #434: Branching needs to account for libuv repositories

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #434

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @halter73

**Comment by halter73** [comment]
Shouldn't this go into release?

**Comment by halter73** [comment]
I guess you've already done branching so this doesn't matter for release

**Comment by pranavkm** [comment]
Yup. This one's for the next branch

**Pull request closed without merging**
