### PR TITLE
Add AspNetCore.Testing.H2Spec.All dependency

### PR DESCRIPTION
**Pull request by Tratcher**
Needed for https://github.com/aspnet/KestrelHttpServer/pull/2653

### CODE REVIEW

**Comment by pranavkm** [comment]
LKGTM. @ryanbrandenburg could you review?

**Comment by Tratcher** [comment]
Coincidence 😁 We did build it ourselves, but it's based on 3rd party content similar to libuv. See https://github.com/summerwind/h2spec/releases

**Comment by halter73** [comment]
@Tratcher Double check your https://github.com/summerwind/h2spec/releases link. It took over a year, but it looks like now it's time to start building and depending on 2.1.1.

**Comment by Tratcher** [comment]
Updated to 2.1.1

**Pull request merged**
