### PR TITLE
Upgrade moq to 4.9.0

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @Eilon  for OSS approval.

@HaoK can you try running a build of this on VSTS before we merge? I'm a little concerned that this might break compilation. The last time we updated Moq there were a few API changes we had to react to.

**Comment by HaoK** [comment]
Sure I'll kick off a PR in VSTS

**Comment by HaoK** [comment]
VSTS Build looks good https://dotnet.visualstudio.com/internal/_build/results?buildId=16639

**Comment by natemcmaster** [comment]
OSS approved: https://dotnet.visualstudio.com/internal/_governance/c641993b-8380-e811-80c3-0004ffb4789e/eed86224-01ac-e811-bce7-00155d7fb5a6

**Pull request merged**
