### PR TITLE
Fix `target-dir-clean` target

### PR DESCRIPTION
**Pull request by dougbu**
- not currently cleaning in most cases
- typo in 16bb0df

### CODE REVIEW

**Comment by dougbu** [comment]
Current version results in errors like `The file '...\artifacts\build\Microsoft.AspNet.Razor\dnx451\Microsoft.AspNet.Razor.dll' already exists.` in the first project that copies into the artifacts folder. Happens any time you run two builds in a row i.e. don't remove the folder or `git clean`.

**Comment by moozzyk** [comment]
:ship::it:

**Comment by dougbu** [comment]
75c1efe

**Pull request merged**
